/**
 * @file coarse_space.hpp
 * @brief Distributed coarse space R_0^T = [R_1^T D_1 Z_1, ..., R_N^T D_N Z_N] and coarse operator A_00.
 */
#ifndef SCHWARZ2LVL_PRECONDITIONER_COARSE_SPACE_HPP
#define SCHWARZ2LVL_PRECONDITIONER_COARSE_SPACE_HPP

#include "coarse_solver.hpp"
#include "subdomain.hpp"
#include "types.hpp"

#include <memory>
#include <string>
#include <vector>

namespace schwarz2lvl::prec {

/**
 * @class CoarseSpace
 * @brief Second level of the Schwarz preconditioner (Section 3.2).
 *
 * Process i owns the m_i coarse unknowns generated by its local basis
 * \f$ V_i = \mathrm{orth}(D_i Z_i) \f$ (same span as D_i Z_i, orthonormal columns
 * for a better conditioned A_00), with global coarse offsets obtained by one
 * MPI_Allgather. Hence
 * \f[ R_0^T = [R_1^T V_1, \dots, R_N^T V_N], \qquad R_0 r = [V_1^T R_1 r; \dots; V_N^T R_N r]. \f]
 *
 * - restrict():  \f$ c_i = V_i^T R_i r \f$ (local; with the Boolean PoU V_i vanishes on the
 *   ghosts, so no halo exchange is needed);
 * - prolong():   \f$ x = \sum_j R_j^T V_j y_j \f$ (local + reverseAdd, again
 *   communication-free with the Boolean PoU);
 * - assemble():  \f$ A_{00} = R_0 A R_0^T \f$ from W = R_0^T restricted to Omega_i:
 *   the owned rows of W are gathered (own V_i rows + neighbours' ghost rows,
 *   only if the PoU is not Boolean), the ghost rows of W are obtained with one
 *   forward exchange of sparse rows, then
 *   \f$ A_{00} = \sum_i W(\Omega_I,:)^T \, A(\Omega_I,\Omega_i)\, W(\Omega_i,:) \f$,
 *   each process computing its term with local products only. The distributed
 *   contributions are summed by the coarse solver (MUMPS distributed input).
 */
class CoarseSpace {
public:
    /**
     * @brief Builds V_i = orth(D_i Z_i) and the coarse numbering (collective).
     * @param sd       Subdomain.
     * @param Z        Local basis Z_i (n_i x k_i) from LocalEigensolver.
     * @param orth_tol Relative rank threshold of the column-pivoted QR.
     */
    CoarseSpace(const part::Subdomain& sd, const core::Mat& Z, double orth_tol);

    /**
     * @brief Assembles and factorizes A_00 = R_0 A R_0^T (collective).
     * @param coarse_solver "auto", "mumps" or "root".
     * @param coarse_procs  Processes of the distributed factorization (0 = all).
     * @param local_solver  Sequential backend of the root solver.
     * @param symmetric     A is symmetric (then A_00 is symmetric).
     */
    void assemble(const std::string& coarse_solver, int coarse_procs, const std::string& local_solver,
                  bool symmetric);

    /// @brief c = V_i^T R_i r (collective only if the PoU is not Boolean).
    void restrict(const core::Vec& r, core::Vec& c) const;
    /// @brief x = sum_j R_j^T V_j y_j, owned entries (collective only if the PoU is not Boolean).
    void prolong(const core::Vec& y, core::Vec& x) const;
    /// @brief y = A_00^{-1} c (collective).
    void solve(const core::Vec& c, core::Vec& y) const;
    /// @brief x = R_0^T A_00^{-1} R_0 r (collective).
    void apply(const core::Vec& r, core::Vec& x) const;

    /// @brief Global coarse dimension n0.
    core::GlobalIndex dimension() const { return offsets_.back(); }
    /// @brief Local contribution m_i.
    core::LocalIndex localDimension() const { return static_cast<core::LocalIndex>(V_.cols()); }
    /// @brief Coarse ownership offsets (size nranks+1).
    const std::vector<core::GlobalIndex>& offsets() const { return offsets_; }
    /// @brief Local orthonormal basis V_i (n_i x m_i).
    const core::Mat& basis() const { return V_; }
    /// @brief Coarse solver (after assemble()).
    const CoarseSolver& solver() const { return *solver_; }
    /// @brief Number of nonzeros of A_00 contributed by this process.
    std::size_t localEntries() const { return local_entries_; }

private:
    const part::Subdomain& sd_;                    ///< Subdomain.
    core::Mat V_;                                  ///< Local basis V_i = orth(D_i Z_i).
    std::vector<core::GlobalIndex> offsets_;       ///< Coarse offsets.
    std::unique_ptr<CoarseSolver> solver_;   ///< Factorization of A_00.
    std::size_t local_entries_ = 0;          ///< Local A_00 contributions.
    mutable core::Vec loc_, c_, y_;                ///< Work vectors.
};

} // namespace schwarz2lvl::prec

#endif // SCHWARZ2LVL_PRECONDITIONER_COARSE_SPACE_HPP
