/**
 * @file coarse_solver.hpp
 * @brief Direct solvers for the coarse problem A_00 y = c (second level).
 */
#ifndef SCHWARZ2LVL_PRECONDITIONER_COARSE_SOLVER_HPP
#define SCHWARZ2LVL_PRECONDITIONER_COARSE_SOLVER_HPP

#include "types.hpp"

#include <mpi.h>

#include <memory>
#include <string>
#include <vector>

namespace schwarz2lvl::prec {

/**
 * @class CoarseSolver
 * @brief Exact solver for the coarse matrix \f$ A_{00} = R_0 A R_0^T \f$.
 *
 * Coarse vectors are distributed like the coarse basis: process i owns the
 * m_i coarse unknowns [offsets[i], offsets[i+1]) generated by its own local
 * basis. The matrix is given as distributed coefficients (duplicates are
 * *summed*), which is exactly the output of the local products
 * W_i^T (A W) computed by CoarseSpace.
 */
class CoarseSolver {
public:
    virtual ~CoarseSolver() = default;

    /**
     * @brief Assembles and factorizes A_00 (collective).
     * @param comm      Communicator of the preconditioner.
     * @param offsets   Coarse ownership offsets (size nranks+1); n0 = offsets.back().
     * @param entries   Local contributions (global coarse indices); may be modified.
     * @param symmetric A_00 is symmetric (only the lower triangle is used).
     */
    virtual void setup(MPI_Comm comm, const std::vector<core::GlobalIndex>& offsets, std::vector<core::GlobalTriplet>& entries,
                       bool symmetric) = 0;

    /**
     * @brief Solves A_00 y = c (collective).
     * @param c Owned coarse entries of the right-hand side (size m_i).
     * @param y Owned coarse entries of the solution (resized to m_i).
     */
    virtual void solve(const core::Vec& c, core::Vec& y) const = 0;

    /// @brief Backend name.
    virtual std::string name() const = 0;
};

/**
 * @brief Creates a coarse solver.
 * @param name         "auto" (mumps if compiled in, else root), "mumps" or "root".
 * @param coarse_procs Number of processes taking part in the distributed
 *                     factorization (0 = all; only for mumps).
 * @param local_solver Sequential backend of the "root" solver.
 */
std::unique_ptr<CoarseSolver> makeCoarseSolver(const std::string& name, int coarse_procs,
                                               const std::string& local_solver);

} // namespace schwarz2lvl::prec

#endif // SCHWARZ2LVL_PRECONDITIONER_COARSE_SOLVER_HPP
